### ISSUE TITLE
sample_app stuck on werkzeug.routing.BuildError: ('debug.debug_root', {}, None)

### ISSUE THREAD

**Issue by ser** [mbr/flask-bootstrap#103]
I am not fully sure if it is a problem in flask-bootstrap or in my implementation of sample_app, which is available here:

https://github.com/ser/topitup/tree/debug-bootstrap-problems

This is what I am getting:

```
$ ./topitup.py 
[24/Jul/2015:18:47:32] ENGINE Bus STARTING
[24/Jul/2015:18:47:32] ENGINE Started monitor thread '_TimeoutMonitor'.
[24/Jul/2015:18:47:32] ENGINE Started monitor thread 'Autoreloader'.
[24/Jul/2015:18:47:33] ENGINE Serving on http://0.0.0.0:1234
[24/Jul/2015:18:47:33] ENGINE Bus STARTED
[24/Jul/2015:18:47:37] ENGINE BuildError('debug.debug_root', {}, None)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1068, in communicate
    req.respond()
  File "/usr/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 856, in respond
    self.server.gateway(self).respond()
  File "/usr/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1958, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/lib/python3.4/site-packages/cherrypy/_cptree.py", line 299, in __call__
    return app(environ, start_response)
  File "/usr/lib/python3.4/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ser/GIT/topitup/frontend.py", line 42, in index
    return render_template('index.html')
  File "/usr/lib/python3.4/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/lib/python3.4/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/home/ser/GIT/topitup/templates/index.html", line 3, in <module>
    {%- extends "base.html" %}
  File "/home/ser/GIT/topitup/templates/base.html", line 19, in <module>
    {% import "bootstrap/fixes.html" as fixes %}
  File "/usr/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in <module>
    {% block doc -%}
  File "/usr/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in <module>
    {%- block html %}
  File "/usr/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in <module>
    {% block body -%}
  File "/usr/lib/python3.4/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in <module>
    {% block navbar %}
  File "/home/ser/GIT/topitup/templates/base.html", line 43, in <module>
    {{nav.frontend_top.render()}}
  File "/usr/lib/python3.4/site-packages/flask_nav/elements.py", line 24, in render
    get_renderer(current_app, renderer)(**kwargs).visit(self)
  File "/usr/lib/python3.4/site-packages/visitor/__init__.py", line 44, in visit
    return meth(node)
  File "/usr/lib/python3.4/site-packages/flask_bootstrap/nav.py", line 53, in visit_Navbar
    bar_list.add(self.visit(item))
  File "/usr/lib/python3.4/site-packages/visitor/__init__.py", line 44, in visit
    return meth(node)
  File "/usr/lib/python3.4/site-packages/flask_bootstrap/nav.py", line 98, in visit_View
    item.add(tags.a(node.text, href=node.get_url(), title=node.text))
  File "/usr/lib/python3.4/site-packages/flask_nav/elements.py", line 73, in get_url
    **self.url_for_kwargs)
  File "/usr/lib/python3.4/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.4/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/usr/lib/python3.4/site-packages/werkzeug/routing.py", line 1678, in build
    raise BuildError(endpoint, values, method)
werkzeug.routing.BuildError: ('debug.debug_root', {}, None)
```

**Comment by mbr** [comment]
It's because you do not have Flask-Debug installed, which is used by the sample application for demonstration purposes. It was missing from the requirements.txt, but I have since then added it. I would suggest to try ``pip install -r sample_app/requirements.txt`` again.

**Comment by ser** [comment]
Hi, yes, you mentioned it and I installed all dependencies, flask-debug works by itself in the same environment, but the sample_app not:

```
$ python
Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flask import Flask
>>> from flask_debug import Debug
>>> app = Flask(__name__)
>>> Debug(app)
<flask_debug.Debug object at 0x7f462eb34048>
>>> app.run(debug=True)
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/usr/bin/python: can't find '__main__' module in ''
```

**Comment by mbr** [comment]
I've clone the ``debug-bootstrap-problems`` branch. First, you're missing a ``requirements.txt`` or a ``setup.py``. Mine had to look like this:

```
cherrypy
flask
paste
flask_bootstrap
flask_appconfig
flask_nav
```

The error you are getting is because there's still a reference to a debug view in the menu. Since you do not have Flask_Debug active on your application (i.e. no ``Debug(app)``), the endpoint ``debug.debug_root`` does not exist.

The sample app uses debug items in the menu, which is not a good idea, it was there only for demonstrational purposes. I would suggest you just remove the line

```python
    View('Debug-Info', 'debug.debug_root'),
```

from ``frontend.py``. I may have to reconsider the sample application and make it actually copy-pastable, if people are going to use it as scaffolding.

On another note: It would have worked if you had used the ``flaskdev`` tool that ships with Flask-Appconfig; if the application is in debug mode, it will slap on a ``Debug(app)`` automatically, allowing you to not have a trace of it in your production code.

Finally and a bit unrelated: I would at least split the WSGI-Server part (CherryPy, paste) and the application. In deployment, it's often necessary to be flexible with the WSGI server implementation (if you're running 10 apps on uwsgi already, you might not want to install CherryPy for number 11).

**Comment by ser** [comment]
Hi, thanks, now I do understand everything :) 

```
from flask_debug import Debug
Debug(app)
```

fixes everything, indeed. 

Thanks for an amazing explanation and advice :)
