### ISSUE TITLE
flaskdev sample_app fails

### ISSUE THREAD

**Issue by fconcklin** [mbr/flask-bootstrap#110]
I have downloaded the flask-bootstrap package and installed the requirements using a virtual environment. However, when I try to run flaskdev sample_app I run into problems with an error message of a non-existent module.  However, in the directory `sample_app` there is an `__init__.py` file. 

   $ pwd
    /Users/fconcklin/src/flask-bootstrap    

    $ flaskdev sample_app
    Traceback (most recent call last):
      File "/Users/fconcklin/telloControl/virt_env/venv/bin/flaskdev", line 11, in <module>
        sys.exit(main())
      File "/Users/fconcklin/telloControl/virt_env/venv/lib/python2.7/site-packages/click/core.py", line 664, in __call__
        return self.main(*args, **kwargs)
      File "/Users/fconcklin/telloControl/virt_env/venv/lib/python2.7/site-packages/click/core.py", line 644, in main
        rv = self.invoke(ctx)
      File "/Users/fconcklin/telloControl/virt_env/venv/lib/python2.7/site-packages/click/core.py", line 837, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/Users/fconcklin/telloControl/virt_env/venv/lib/python2.7/site-packages/click/core.py", line 464, in invoke
        return callback(*args, **kwargs)
      File "/Users/fconcklin/telloControl/virt_env/venv/lib/python2.7/site-packages/flask_appconfig/cli.py", line 77, in main
        mod = importlib.import_module(module_name)
      File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named sample_app

**Comment by mbr** [comment]
This is actually a bug in ``flaskdev``, for which I have not decided yet whether or not it should be a feature.

Currently, ``flaskdev`` will not change ``sys.path``, so the app must be on your path. Try ``pip install -e`` in the clone ``flask-bootstrap`` repo, the ``find_packages`` call will "install" ``sample_app`` (from that point on you can ``import sample_app`` in a regular Python interpreter as well).

I admit it's confusing and I will do something about it, soon.

**Comment by mbr** [comment]
Fixed in Flask-Appconfig master branch; now appends ``'.'`` to ``sys.path``
